In [41]:
import finnhub 
#Convert to Pandas Dataframe
import pandas as pd
from datetime import datetime
import yfinance as yf
import alpaca_trade_api as tradeapi
import os

FINNHUB_API_KEY = 'bvcebsf48v6v1cifk3j0'
API_KEY = "PKEF15JBO0QFAXPX8G9J"
API_SECRET = "LPLbMcagNZ8XYwUslIY1vSlnIoe1c7yFdhNYR58C"
APCA_API_BASE_URL = "https://paper-api.alpaca.markets"

os.environ.setdefault('APCA_API_KEY_ID', API_KEY)
os.environ.setdefault('APCA_API_SECRET_KEY', API_SECRET)
os.environ.setdefault('APCA_API_BASE_URL', APCA_API_BASE_URL)
os.environ.setdefault('APCA_RETRY_MAX', 10)
os.environ.setdefault('APCA_RETRY_WAIT', 10)

'https://paper-api.alpaca.markets'

In [87]:
df = pd.read_csv('constituents_csv.csv')

In [91]:
tickers_list = list(df.Symbol)

In [92]:
tickers_list

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADBE',
 'AAP',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALXN',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'APA',
 'AIV',
 'AAPL',
 'AMAT',
 'APTV',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BKR',
 'BLL',
 'BAC',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'BIIB',
 'BLK',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BF.B',
 'CHRW',
 'COG',
 'CDNS',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'CNC',
 'CNP',
 'CTL',
 'CERN',
 'CF',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'CXO',
 'COP',
 'ED',
 'STZ',
 'CPRT',
 'GLW',
 'CTVA',
 'COST',
 'COTY',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DTE',
 'DUK',
 'DRE',
 'DD',
 'DXC',
 'ETFC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'EMR',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'RE',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FRC',
 'FE',
 'FISV',
 'FLT',
 'FLIR',
 'FLS',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'GWW',
 'HRB',
 'HAL',
 'HBI',
 'HIG',
 'HAS',
 'HCA',
 'PEAK',
 'HSIC',
 'HES',
 'HPE',
 'HLT',
 'HFC',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IEX',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'INTC',
 'ICE',
 'IBM',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JBHT',
 'JKHY',
 'J',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KSS',
 'KHC',
 'KR',
 'LB',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LEG',
 'LDOS',
 'LEN',
 'LLY',
 'LNC',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MXIM',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MHK',
 'TAP',
 'MDLZ',
 'MNST',
 'MCO',
 'MS',
 'MSI',
 'MSCI',
 'MYL',
 'NDAQ',
 'NOV',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NBL',
 'NSC',
 'NTRS',
 'NOC',
 'NLOK',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PRGO',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'QCOM',
 'PWR',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SLG',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STE',
 'SYK',
 'SIVB',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'FTI',
 'TDY',
 'TFX',
 'TXN',
 'TXT',
 'BK',
 'CLX',
 'COO',
 'HSY',
 'MOS',
 'TRV',
 'DIS',
 'TMO',
 'TIF',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TFC',
 'TWTR',
 'TYL',
 'TSN',
 'USB',
 'UDR',
 'ULTA',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UNH',
 'UPS',
 'URI',
 'UHS',
 'UNM',
 'VLO',
 'VAR',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VFC',
 'VIAC',
 'V',
 'VNO',
 'VMC',
 'WRB',
 'WAB',
 'WBA',
 'WMT',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XRX',
 'XLNX',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

# YFinance to Fetch and Store Daily Stock Data

In [83]:
ticker = "MSFT AAPL IBM" # or tickers

In [84]:
data = yf.download(ticker, period='max', group_by="ticker", threads=2)
data

[*********************100%***********************]  3 of 3 completed

                  MSFT                                                  \
                  Open        High         Low       Close   Adj Close
Date
1962-01-02         NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2020-12-28  224.449997  226.029999  223.020004  224.960007  224.960007
2020-12-29  226.309998  227.179993  223.580002  224.149994  224.149994
2020-12-30  225.229996  225.630005  221.470001  221.679993  221.679993
2020-12-31  221.699997  223.000000  219.679993  222.419998  222.419998
2021-01-04  222.529999  223.000000  214.809998  217.690002  217.690002

                              AAPL                                      \
                Volume        Open        High         Low       Close
Date
1962-01-02         NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2020-12-28  17933500.0  133.990005  137.339996  133.509995  136.690002
2020-12-29  17403200.0  138.050003  138.789993  134.339996  134.869995
2020-12-30  20272300.0  135.580002  135.990005  133.399994  133.720001
2020-12-31  20926900.0  134.080002  134.740005  131.720001  132.690002
2021-01-04  37113600.0  133.520004  133.610001  126.760002  129.410004

                                            IBM                          \
             Adj Close       Volume        Open        High         Low
Date
1962-01-02         NaN          NaN    7.713333    7.713333    7.626667
1962-01-03         NaN          NaN    7.626667    7.693333    7.626667
1962-01-04         NaN          NaN    7.693333    7.693333    7.613333
1962-01-05         NaN          NaN    7.606667    7.606667    7.453333
1962-01-08         NaN          NaN    7.460000    7.460000    7.266667
...                ...          ...         ...         ...         ...
2020-12-28  136.690002  124486200.0  125.099998  126.599998  124.459999
2020-12-29  134.869995  121047300.0  125.349998  125.480003  123.239998
2020-12-30  133.720001   96452100.0  123.800003  124.849998  123.629997
2020-12-31  132.690002   98990400.0  124.220001  126.029999  123.989998
2021-01-04  129.410004  143129000.0  125.849998  125.919998  123.040001


                 Close   Adj Close   Volume
Date
1962-01-02    7.626667    1.850917   387200
1962-01-03    7.693333    1.867095   288000
1962-01-04    7.616667    1.848488   256000
1962-01-05    7.466667    1.812086   363200
1962-01-08    7.326667    1.778110   544000
...                ...         ...      ...
2020-12-28  124.820000  124.820000  3615200
2020-12-29  123.800003  123.800003  3487000
2020-12-30  124.339996  124.339996  3380300
2020-12-31  125.879997  125.879997  3574400
2021-01-04  123.940002  123.940002  5177000

[14854 rows x 18 columns]

In [46]:
api = tradeapi.REST()

In [48]:
# Minute data example TRADE API
NY = 'America/New_York'
start=pd.Timestamp('1990-08-28 9:30', tz=NY).isoformat()
end=pd.Timestamp('2020-08-28 16:00', tz=NY).isoformat()
print(api.get_barset(['AAPL', 'MSFT'], 'minute', start=start, end=end).df)

                              AAPL                                       MSFT  \
                              open     high     low   close   volume     open
time
2015-01-02 08:09:00-05:00  111.080  111.080  111.08  111.08    100.0      NaN
2015-01-02 08:46:00-05:00  111.280  111.280  111.28  111.28    100.0      NaN
2015-01-02 08:48:00-05:00  111.340  111.340  111.34  111.34    100.0      NaN
2015-01-02 09:21:00-05:00  111.420  111.420  111.42  111.42    100.0      NaN
2015-01-02 09:30:00-05:00  111.400  111.400  111.24  111.26   3052.0   46.670
...                            ...      ...     ...     ...      ...      ...
2020-08-28 15:55:00-04:00  499.395  500.736  499.32  500.64  15712.0  228.640
2020-08-28 15:56:00-04:00  500.630  500.630  498.97  499.26  28614.0  228.645
2020-08-28 15:57:00-04:00  499.120  500.730  499.03  499.99  19125.0  228.690
2020-08-28 15:58:00-04:00  499.950  499.970  499.29  499.54  28301.0  228.900
2020-08-28 15:59:00-04:00  499.545  499.700  498.94  499.18  19513.0  229.020


                             high     low   close   volume
time
2015-01-02 08:09:00-05:00     NaN     NaN     NaN      NaN
2015-01-02 08:46:00-05:00     NaN     NaN     NaN      NaN
2015-01-02 08:48:00-05:00     NaN     NaN     NaN      NaN
2015-01-02 09:21:00-05:00     NaN     NaN     NaN      NaN
2015-01-02 09:30:00-05:00   46.69   46.64   46.69   3465.0
...                           ...     ...     ...      ...
2020-08-28 15:55:00-04:00  228.73  228.45  228.67   5044.0
2020-08-28 15:56:00-04:00  228.72  228.60  228.65   5518.0
2020-08-28 15:57:00-04:00  228.98  228.69  228.95   7400.0
2020-08-28 15:58:00-04:00  229.03  228.90  229.03   5714.0
2020-08-28 15:59:00-04:00  229.12  228.95  228.95  12223.0

[567899 rows x 10 columns]

In [79]:
# Minute data example POLYGON
import pytz
import sys
NY = 'America/New_York'
df_list = []
start = pd.Timestamp('2004-01-02 09:30', tz=NY).value/1e6
end = pd.Timestamp('2020-01-02 16:00', tz=NY).value/1e6

In [81]:
from IPython.display import clear_output
while start < end:
    df = api.polygon.historic_agg_v2('AAPL', 1, 'minute', _from=start, to=end).df
    df_list.append(df)
    start = df.index[-1].value/1e6
    clear_output(wait=True)
    print(f'current date: {df.index[-1]}')

current date: 2020-01-02 16:00:00-05:00

In [85]:
new_df = pd.concat(df_list)
new_df

,open,high,low,close,volume,vwap
timestamp,,,,,,
2004-01-02 09:30:00-05:00,0.3848,0.3866,0.3847,0.3863,2113944.0,0.3851
2004-01-02 09:31:00-05:00,0.3848,0.3873,0.3847,0.3868,964936.0,0.3863
2004-01-02 09:32:00-05:00,0.3869,0.3884,0.3863,0.3884,1960952.0,0.3865
2004-01-02 09:33:00-05:00,0.3882,0.3884,0.3875,0.3882,459200.0,0.3879
2004-01-02 09:34:00-05:00,0.3882,0.3884,0.3875,0.3875,584416.0,0.3878
...,...,...,...,...,...,...
2020-01-02 15:56:00-05:00,75.0275,75.0750,75.0275,75.0600,944808.0,75.0563
2020-01-02 15:57:00-05:00,75.0600,75.0750,75.0550,75.0700,711972.0,75.0649
2020-01-02 15:58:00-05:00,75.0750,75.1050,75.0500,75.1000,1028952.0,75.0771
2020-01-02 15:59:00-05:00,75.1000,75.1500,75.0850,75.1450,2067704.0,75.1127
2020-01-02 16:00:00-05:00,75.0875,75.1200,75.0875,75.1050,1548004.0,75.0877